source "https://rubygems.org"
  
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'byebug'

gem "sqlite3", "~> 1.4.0"
gem 'pry'
gem 'rake'
gem 'require_all'
# gem 'activerecord'
gem 'activerecord', "~>6.1.7"
gem 'sinatra-activerecord'
gem 'rest-client'
